networks:
  paradb.net:
    driver: bridge

services:

  phpparadb:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '1080:80'
    volumes:
      - ./td1:/var/php/td1
      - ./td2:/var/php/td2
      - ./td3:/var/php/td3
      - ./td4:/var/php/td4
      - ./sql:/var/sql
    working_dir: /var/php
    networks:
      - paradb.net
    depends_on:
      paradb.db:
        condition: service_healthy
      pgsql.db:
        condition: service_healthy
    command: php -S 0.0.0.0:80 -t /var/php
    restart: unless-stopped

  paradb.db:
    image: 'mariadb:11.6.2-noble'
    env_file: ./paradb.env
    ports:
      - '1081:3306'
    networks:
      - paradb.net
    restart: unless-stopped
    volumes:
      - ./sql:/var/sql
    healthcheck:
      test: ["CMD-SHELL", 'mariadb-admin ping -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}']
      interval: 2s
      timeout: 2s
      retries: 10

  pgsql.db:
    image: 'postgres:latest'
    env_file: ./paradbpgsql.env
    networks:
      - paradb.net
    restart: unless-stopped
    volumes:
      - ./pgsql:/var/sql
    ports:
      - '1083:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      retries: 5
      timeout: 10s

  adminer:
    image: 'adminer'
    ports:
      - '1082:8080'
    networks:
      - paradb.net
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: unless-stopped


