networks:
  paradb.net:
    driver: bridge

services:

  phpparadb:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '1081:80'
    volumes:
      - ./.:/var/php/
      - ./sql:/var/sql
    working_dir: /var/php
    networks:
      - paradb.net
    command: php -S 0.0.0.0:80 -t /var/php
    restart: unless-stopped

  paradb.db:
    image: 'mariadb:11.6.2-noble'
    env_file: ./paradb.env
    ports:
      - '1082:3306'
    networks:
      - paradb.net
    restart: unless-stopped
    volumes:
      - ./sql:/var/sql

  mongo:
    image: mongo:latest
    volumes:
    - ./mongo:/var/data
    working_dir: /var/data
    networks:
    - paradb.net
    ports:
    - 27018:27017
